<?php

namespace App\Models\Pterodactyl;

use App\Classes\PterodactylClient;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use App\Models\Product;

class Egg extends Model
{
    use HasFactory;

    public $incrementing = false;

    protected $fillable = [
        'id',
        'tags',
        'name',
        'description',
        'docker_image',
        'startup',
        'environment',
        'updated_at',
    ];

    protected $casts = [
        'environment' => 'array',
        'tags' => 'array',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function (Egg $egg) {
            $egg->products()->detach();
        });
    }

    public static function syncEggs()
    {
        $client = app(PterodactylClient::class);
        $eggs = $client->getEggs();

        foreach ($eggs as $egg) {
            $array = [];
            $environment = [];

            $array['id'] = $egg['attributes']['id'];
            $array['tags'] = $egg['attributes']['tags'];
            $array['name'] = $egg['attributes']['name'];
            $array['description'] = $egg['attributes']['description'];
            $array['docker_image'] = $egg['attributes']['docker_image'];
            $array['startup'] = $egg['attributes']['startup'];
            $array['updated_at'] = now();

            //get environment variables
            foreach ($egg['attributes']['relationships']['variables']['data'] as $variable) {
                $environment[] = [
                    'name' => $variable['attributes']['name'],
                    'description' => $variable['attributes']['description'],
                    'default_value' => $variable['attributes']['default_value'],
                    'env_variable' => $variable['attributes']['env_variable'],
                    'user_viewable' => $variable['attributes']['user_viewable'],
                    'user_editable' => $variable['attributes']['user_editable'],
                    'rules' => $variable['attributes']['rules'],
                ];
            }

            $array['environment'] = $environment;

            self::query()->updateOrCreate([
                'id' => $array['id'],
            ], array_diff_key($array, array_flip(['id']))
            );
        }

        self::removeDeletedEggs($eggs);
    }

    /**
     * @description remove eggs that have been deleted on pterodactyl
     *
     * @param  array  $eggs
     */
    private static function removeDeletedEggs(array $eggs): void
    {
        $ids = array_map(function ($data) {
            return $data['attributes']['id'];
        }, $eggs);

        self::whereNotIn('id', $ids)->delete();
    }

    /**
     * @return BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
}
